//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEPData
    {
        public BEPData()
        {
            this.BERDataPeopleWiseQuantities = new HashSet<BERDataPeopleWiseQuantity>();
            this.BERDataItemWiseQuantities = new HashSet<BERDataItemWiseQuantity>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int ProgramId { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int UpazilaCoverageCount { get; set; }
        public string UpazillaRemarks { get; set; }
        public Nullable<int> ImpactProgramId { get; set; }
        public Nullable<int> RestrictonId { get; set; }
        public int AffectedBracWorkerCount { get; set; }
        public int WorkFromHomeStaffCount { get; set; }
        public decimal FinancialLoss { get; set; }
        public Nullable<int> ComMaterialId { get; set; }
        public Nullable<int> ComChannelId { get; set; }
        public int Target { get; set; }
        public string Remarks { get; set; }
        public int InsertedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual BEPData BEPData1 { get; set; }
        public virtual BEPData BEPData2 { get; set; }
        public virtual StandingData StandingData { get; set; }
        public virtual StandingData StandingData1 { get; set; }
        public virtual StandingData StandingData2 { get; set; }
        public virtual StandingData StandingData3 { get; set; }
        public virtual StandingData StandingData4 { get; set; }
        public virtual StandingData StandingData5 { get; set; }
        public virtual StandingData StandingData6 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<BERDataPeopleWiseQuantity> BERDataPeopleWiseQuantities { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities { get; set; }
    }
}
