//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictSummery
    {
        public int Id { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int HospitalCount { get; set; }
        public int BedCount { get; set; }
        public int IcuCount { get; set; }
        public string Remarks { get; set; }
        public int InsertedById { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int TotalQuarantine { get; set; }
        public int TotalReleased { get; set; }
        public int CurrentQuarantine { get; set; }
        public int TotalDoTestOn { get; set; }
        public int TotalDeath { get; set; }
        public int TotalReliefFamily { get; set; }
        public int TotalReliefPerson { get; set; }
        public decimal TotalRice { get; set; }
        public decimal TotalDal { get; set; }
        public decimal TotalPotato { get; set; }
        public int TotalMoney { get; set; }
        public decimal TotalOnion { get; set; }
        public decimal TotalSalt { get; set; }
        public decimal TotalOil { get; set; }
        public decimal TotalSoap { get; set; }
        public int OtherPatientCount { get; set; }
        public int BreathingPatientCount { get; set; }
        public int MaternalCount { get; set; }
        public decimal PlannedRice { get; set; }
        public decimal PlannedPotato { get; set; }
        public decimal PlannedDal { get; set; }
        public decimal PlannedMoney { get; set; }
        public Nullable<int> PeopleIndex { get; set; }
        public Nullable<int> HealthIndex { get; set; }
        public Nullable<int> SupportIndex { get; set; }
        public Nullable<int> BracIndex { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> StaffWorkFromHome { get; set; }
        public Nullable<int> StaffAffected { get; set; }
        public Nullable<int> BracFinancialLoss { get; set; }
        public Nullable<int> StaffMaleReach { get; set; }
        public Nullable<int> StaffFemaleReach { get; set; }
        public Nullable<int> SummerizedData_ReachCount { get; set; }
        public Nullable<int> DetailData_TotalCount { get; set; }
        public Nullable<int> DetailData_MaleCount { get; set; }
        public Nullable<int> DetailData_FemaleCount { get; set; }
        public Nullable<decimal> DetailData_MalePercent { get; set; }
        public Nullable<decimal> DetailData_FemalePercent { get; set; }
        public Nullable<int> PovertyRank { get; set; }
        public Nullable<int> ExtreamPovertyRank { get; set; }
        public Nullable<int> BracMoneyDistribution { get; set; }
        public Nullable<int> BracFoodDistribution { get; set; }
        public string DistrictCode { get; set; }
        public Nullable<int> PatientCount { get; set; }
        public int TotalBracPatient { get; set; }
        public int TotalBracReleased { get; set; }
        public int TotalBracQurantine { get; set; }
        public Nullable<System.DateTime> PriceDate { get; set; }
        public Nullable<int> PriceRice { get; set; }
        public Nullable<int> PriceDal { get; set; }
        public Nullable<int> PricePotato { get; set; }
        public Nullable<int> PriceOnion { get; set; }
        public Nullable<int> PriceOil { get; set; }
        public Nullable<int> PriceOilPack { get; set; }
        public Nullable<int> PriceSalt { get; set; }
        public Nullable<int> PriceEggPlant { get; set; }
        public Nullable<int> PriceEgg { get; set; }
        public Nullable<int> PriceChille { get; set; }
        public Nullable<int> PricePumpkin { get; set; }
        public string PriceComment { get; set; }
        public Nullable<int> AgroLaborSalaryMale { get; set; }
        public Nullable<int> AgroLaborExpMale { get; set; }
        public Nullable<int> CarpenterSalaryMale { get; set; }
        public Nullable<int> CarpenterAssSalaryMale { get; set; }
        public Nullable<int> RickPullIncome { get; set; }
        public Nullable<int> RickPullExp { get; set; }
        public Nullable<int> AgroLaborSalaryFemale { get; set; }
        public Nullable<int> AgroLaborExpFemale { get; set; }
        public Nullable<int> CarpenterAssSalaryFemale { get; set; }
    
        public virtual StandingData StandingData { get; set; }
        public virtual StandingData StandingData1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
