//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictData
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int NewQuarantine { get; set; }
        public int ReleasedQuarantine { get; set; }
        public int DoTestOn { get; set; }
        public int Death { get; set; }
        public int InsertedById { get; set; }
        public string LocalAdminMeasure { get; set; }
        public string Demand { get; set; }
        public string Panic { get; set; }
        public string SocialIssue { get; set; }
        public string NgoDoing { get; set; }
        public string NeedyPeople { get; set; }
        public string BracDo { get; set; }
        public string Remarks { get; set; }
        public int MemberCount { get; set; }
        public int MemberUpazillaCount { get; set; }
        public string BracThink { get; set; }
        public int ReliefFamily { get; set; }
        public int ReliefPerson { get; set; }
        public decimal Rice { get; set; }
        public decimal Dal { get; set; }
        public decimal Potato { get; set; }
        public int Money { get; set; }
        public decimal Onion { get; set; }
        public decimal Salt { get; set; }
        public decimal Oil { get; set; }
        public decimal Soap { get; set; }
        public int TillQuarantine { get; set; }
        public int TillReleasedQuarantine { get; set; }
        public int TillDoTestOn { get; set; }
        public int TillDeath { get; set; }
        public int TillCurrentQuarantine { get; set; }
        public string ReliefRemarks { get; set; }
        public int HospitalCount { get; set; }
        public int BedCount { get; set; }
        public int IcuCount { get; set; }
        public int OtherPatientCount { get; set; }
        public int BreathingPatientCount { get; set; }
        public int MaternalCount { get; set; }
        public Nullable<int> Question1Id { get; set; }
        public string Answer1 { get; set; }
        public Nullable<int> Question2Id { get; set; }
        public string Answer2 { get; set; }
        public int BracPatient { get; set; }
        public int BracReleased { get; set; }
        public int BracQurantine { get; set; }
        public int TillBracPatient { get; set; }
        public int TillBracReleased { get; set; }
        public int TillBracQurantine { get; set; }
    
        public virtual StandingData StandingData { get; set; }
        public virtual StandingData StandingData1 { get; set; }
        public virtual StandingData StandingData2 { get; set; }
        public virtual StandingData StandingData3 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
