//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictSummery
    {
        public int Id { get; set; }
        public int DivisionId { get; set; }
        public int DistrictId { get; set; }
        public int HospitalCount { get; set; }
        public int BedCount { get; set; }
        public int IcuCount { get; set; }
        public string Remarks { get; set; }
        public int InsertedById { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public int TotalQuarantine { get; set; }
        public int TotalReleased { get; set; }
        public int CurrentQuarantine { get; set; }
        public int TotalDoTestOn { get; set; }
        public int TotalDeath { get; set; }
        public int TotalReliefFamily { get; set; }
        public int TotalReliefPerson { get; set; }
        public decimal TotalRice { get; set; }
        public decimal TotalDal { get; set; }
        public decimal TotalPotato { get; set; }
        public int TotalMoney { get; set; }
        public decimal TotalOnion { get; set; }
        public decimal TotalSalt { get; set; }
        public decimal TotalOil { get; set; }
        public decimal TotalSoap { get; set; }
        public int OtherPatientCount { get; set; }
        public int BreathingPatientCount { get; set; }
        public int MaternalCount { get; set; }
        public decimal PlannedRice { get; set; }
        public decimal PlannedPotato { get; set; }
        public decimal PlannedDal { get; set; }
        public decimal PlannedMoney { get; set; }
    
        public virtual StandingData StandingData { get; set; }
        public virtual StandingData StandingData1 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
