//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorPoleCouncilling
    {
        public int Id { get; set; }
        public int DoctorPoleId { get; set; }
        public string Advice { get; set; }
        public string Comment { get; set; }
        public int InsertedById { get; set; }
        public System.DateTime InsertionTime { get; set; }
    
        public virtual DoctorsPole DoctorsPole { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
