//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorPoleStatus
    {
        public int Id { get; set; }
        public int DoctorPoleId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual DoctorsPole DoctorsPole { get; set; }
        public virtual StandingData StandingData { get; set; }
    }
}
