//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsPoleVisit
    {
        public DoctorsPoleVisit()
        {
            this.DoctorsPoleVisitDetails = new HashSet<DoctorsPoleVisitDetail>();
        }
    
        public int Id { get; set; }
        public int DoctorPoleId { get; set; }
        public bool IsFever { get; set; }
        public bool IsDryCough { get; set; }
        public bool IsSoreThroat { get; set; }
        public bool IsBreathing { get; set; }
        public string OtherSymptoms { get; set; }
        public Nullable<bool> AdvConTreat { get; set; }
        public Nullable<bool> Adv { get; set; }
        public Nullable<bool> AdvQurentine { get; set; }
        public Nullable<bool> AdvHomeIsolation { get; set; }
        public Nullable<bool> AdvReferHospital { get; set; }
        public Nullable<bool> IsAntibioticTaken { get; set; }
        public int StatusId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CoMorbidityId { get; set; }
        public Nullable<System.DateTime> SampleTakenDate { get; set; }
        public Nullable<int> TestResultId { get; set; }
        public Nullable<System.DateTime> TestResultDate { get; set; }
        public Nullable<int> AdmittedTypeId { get; set; }
        public string HospitalName { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public string AlternatePhoneNo { get; set; }
        public string AlternateName { get; set; }
        public int EntryById { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<int> LastUpdateById { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string CoMorbidities { get; set; }
        public Nullable<System.DateTime> SampleTakenDate1 { get; set; }
        public Nullable<int> TestResultId1 { get; set; }
        public Nullable<System.DateTime> TestResultDate1 { get; set; }
        public Nullable<System.DateTime> SampleTakenDate2 { get; set; }
        public Nullable<int> TestResultId2 { get; set; }
        public Nullable<System.DateTime> TestResultDate2 { get; set; }
    
        public virtual DoctorsPole DoctorsPole { get; set; }
        public virtual ICollection<DoctorsPoleVisitDetail> DoctorsPoleVisitDetails { get; set; }
        public virtual StandingData StandingData { get; set; }
        public virtual StandingData StandingData1 { get; set; }
        public virtual StandingData StandingData2 { get; set; }
        public virtual StandingData StandingData3 { get; set; }
        public virtual StandingData StandingData4 { get; set; }
        public virtual StandingData StandingData5 { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
