//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsPoleVisitDetail
    {
        public int Id { get; set; }
        public int DoctorsPoleVisitId { get; set; }
        public string RelationType { get; set; }
        public int RelationStandingDataId { get; set; }
    
        public virtual DoctorsPoleVisit DoctorsPoleVisit { get; set; }
        public virtual StandingData StandingData { get; set; }
    }
}
