//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandingData
    {
        public StandingData()
        {
            this.BEPDatas = new HashSet<BEPData>();
            this.BEPDatas1 = new HashSet<BEPData>();
            this.BEPDatas2 = new HashSet<BEPData>();
            this.BEPDatas3 = new HashSet<BEPData>();
            this.BEPDatas4 = new HashSet<BEPData>();
            this.BEPDatas5 = new HashSet<BEPData>();
            this.BEPDatas6 = new HashSet<BEPData>();
            this.BERDataItemWiseQuantities = new HashSet<BERDataItemWiseQuantity>();
            this.BERDataItemWiseQuantities1 = new HashSet<BERDataItemWiseQuantity>();
            this.BERDataItemWiseQuantities2 = new HashSet<BERDataItemWiseQuantity>();
            this.BERDataItemWiseQuantities3 = new HashSet<BERDataItemWiseQuantity>();
            this.BERDataItemWiseQuantities4 = new HashSet<BERDataItemWiseQuantity>();
            this.BERDataPeopleWiseQuantities = new HashSet<BERDataPeopleWiseQuantity>();
            this.BERDataPeopleWiseQuantities1 = new HashSet<BERDataPeopleWiseQuantity>();
            this.BERDataPeopleWiseQuantities2 = new HashSet<BERDataPeopleWiseQuantity>();
            this.BERDataPeopleWiseQuantities3 = new HashSet<BERDataPeopleWiseQuantity>();
            this.DetailDatas = new HashSet<DetailData>();
            this.DetailDatas1 = new HashSet<DetailData>();
            this.DetailDatas2 = new HashSet<DetailData>();
            this.DetailDatas3 = new HashSet<DetailData>();
            this.DetailDatas4 = new HashSet<DetailData>();
            this.DistrictByUserProfiles = new HashSet<DistrictByUserProfile>();
            this.DistrictDatas = new HashSet<DistrictData>();
            this.DistrictDatas1 = new HashSet<DistrictData>();
            this.DistrictDatas2 = new HashSet<DistrictData>();
            this.DistrictDatas3 = new HashSet<DistrictData>();
            this.DistrictPatients = new HashSet<DistrictPatient>();
            this.DistrictQuestions = new HashSet<DistrictQuestion>();
            this.DistrictQuestions1 = new HashSet<DistrictQuestion>();
            this.DistrictSummeries = new HashSet<DistrictSummery>();
            this.DistrictSummeries1 = new HashSet<DistrictSummery>();
            this.DoctorPoleStatuses = new HashSet<DoctorPoleStatus>();
            this.DoctorsPoles = new HashSet<DoctorsPole>();
            this.DoctorsPoles1 = new HashSet<DoctorsPole>();
            this.DoctorsPoles2 = new HashSet<DoctorsPole>();
            this.DoctorsPoles3 = new HashSet<DoctorsPole>();
            this.DoctorsPoles4 = new HashSet<DoctorsPole>();
            this.DoctorsPoles5 = new HashSet<DoctorsPole>();
            this.DoctorsPoles6 = new HashSet<DoctorsPole>();
            this.DoctorsPoles7 = new HashSet<DoctorsPole>();
            this.DoctorsPoles8 = new HashSet<DoctorsPole>();
            this.DoctorsPoles9 = new HashSet<DoctorsPole>();
            this.DoctorsPoles10 = new HashSet<DoctorsPole>();
            this.DoctorsPoles11 = new HashSet<DoctorsPole>();
            this.DoctorsPoleVisitDetails = new HashSet<DoctorsPoleVisitDetail>();
            this.DoctorsPoleVisits = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits1 = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits2 = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits3 = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits4 = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits5 = new HashSet<DoctorsPoleVisit>();
            this.DoctorsPoleVisits6 = new HashSet<DoctorsPoleVisit>();
            this.HnppDatas = new HashSet<HnppData>();
            this.HnppDatas1 = new HashSet<HnppData>();
            this.ProgramByUserProfiles = new HashSet<ProgramByUserProfile>();
            this.StandingDataPcRelations = new HashSet<StandingDataPcRelation>();
            this.StandingDataPcRelations1 = new HashSet<StandingDataPcRelation>();
            this.SummerizedDatas = new HashSet<SummerizedData>();
            this.SummerizedDatas1 = new HashSet<SummerizedData>();
            this.SummerizedDatas2 = new HashSet<SummerizedData>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> IntValue { get; set; }
        public string StringValue { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> People { get; set; }
    
        public virtual ICollection<BEPData> BEPDatas { get; set; }
        public virtual ICollection<BEPData> BEPDatas1 { get; set; }
        public virtual ICollection<BEPData> BEPDatas2 { get; set; }
        public virtual ICollection<BEPData> BEPDatas3 { get; set; }
        public virtual ICollection<BEPData> BEPDatas4 { get; set; }
        public virtual ICollection<BEPData> BEPDatas5 { get; set; }
        public virtual ICollection<BEPData> BEPDatas6 { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities1 { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities2 { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities3 { get; set; }
        public virtual ICollection<BERDataItemWiseQuantity> BERDataItemWiseQuantities4 { get; set; }
        public virtual ICollection<BERDataPeopleWiseQuantity> BERDataPeopleWiseQuantities { get; set; }
        public virtual ICollection<BERDataPeopleWiseQuantity> BERDataPeopleWiseQuantities1 { get; set; }
        public virtual ICollection<BERDataPeopleWiseQuantity> BERDataPeopleWiseQuantities2 { get; set; }
        public virtual ICollection<BERDataPeopleWiseQuantity> BERDataPeopleWiseQuantities3 { get; set; }
        public virtual ICollection<DetailData> DetailDatas { get; set; }
        public virtual ICollection<DetailData> DetailDatas1 { get; set; }
        public virtual ICollection<DetailData> DetailDatas2 { get; set; }
        public virtual ICollection<DetailData> DetailDatas3 { get; set; }
        public virtual ICollection<DetailData> DetailDatas4 { get; set; }
        public virtual ICollection<DistrictByUserProfile> DistrictByUserProfiles { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas1 { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas2 { get; set; }
        public virtual ICollection<DistrictData> DistrictDatas3 { get; set; }
        public virtual ICollection<DistrictPatient> DistrictPatients { get; set; }
        public virtual ICollection<DistrictQuestion> DistrictQuestions { get; set; }
        public virtual ICollection<DistrictQuestion> DistrictQuestions1 { get; set; }
        public virtual ICollection<DistrictSummery> DistrictSummeries { get; set; }
        public virtual ICollection<DistrictSummery> DistrictSummeries1 { get; set; }
        public virtual ICollection<DoctorPoleStatus> DoctorPoleStatuses { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles1 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles2 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles3 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles4 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles5 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles6 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles7 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles8 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles9 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles10 { get; set; }
        public virtual ICollection<DoctorsPole> DoctorsPoles11 { get; set; }
        public virtual ICollection<DoctorsPoleVisitDetail> DoctorsPoleVisitDetails { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits1 { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits2 { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits3 { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits4 { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits5 { get; set; }
        public virtual ICollection<DoctorsPoleVisit> DoctorsPoleVisits6 { get; set; }
        public virtual ICollection<HnppData> HnppDatas { get; set; }
        public virtual ICollection<HnppData> HnppDatas1 { get; set; }
        public virtual ICollection<ProgramByUserProfile> ProgramByUserProfiles { get; set; }
        public virtual ICollection<StandingDataPcRelation> StandingDataPcRelations { get; set; }
        public virtual ICollection<StandingDataPcRelation> StandingDataPcRelations1 { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas1 { get; set; }
        public virtual ICollection<SummerizedData> SummerizedDatas2 { get; set; }
    }
}
