//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UomOfProduct
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int UomId { get; set; }
        public int Ordering { get; set; }
        public bool IsDefault { get; set; }
        public bool IsPurchaseable { get; set; }
        public Nullable<decimal> PurchaseRate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Uom Uom { get; set; }
    }
}
