//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppProj.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkstationLeaveQuarantine
    {
        public int Id { get; set; }
        public string PIN { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string Grade { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string HomeDistrict { get; set; }
        public Nullable<System.DateTime> DateOfJoiningBrac { get; set; }
        public Nullable<System.DateTime> DateOfJoiningCurrentBranch { get; set; }
        public string Branch { get; set; }
        public string Area { get; set; }
        public string Region { get; set; }
        public Nullable<int> UpazillaId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public bool IsWorkStationLeft { get; set; }
        public Nullable<System.DateTime> WorkStationLeaveDate { get; set; }
        public Nullable<System.DateTime> WorkStationReturnDate { get; set; }
        public string SupervisorPermitted { get; set; }
        public bool IsStayInQuarantine { get; set; }
        public Nullable<System.DateTime> QuarantineStartDate { get; set; }
        public Nullable<System.DateTime> QuarantineEndDate { get; set; }
        public bool IsCoronaSymptomitic { get; set; }
        public bool IsQuarantineExtended { get; set; }
        public Nullable<System.DateTime> ExtendedQuarantineStartDate { get; set; }
        public Nullable<System.DateTime> ExtendedQuarantineEndDate { get; set; }
        public string InfoCollectedName { get; set; }
        public string InfoCollectedPIN { get; set; }
        public string InfoCollectedDesignation { get; set; }
        public Nullable<System.DateTime> InfoCollectedDate { get; set; }
        public string Comment { get; set; }
        public int EntryById { get; set; }
        public System.DateTime EntryTime { get; set; }
        public Nullable<int> LastUpdateById { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public bool IsInformationFromAnotherPerson { get; set; }
        public Nullable<bool> IsWorkStationLeftByDoctor { get; set; }
        public Nullable<System.DateTime> WorkStationLeftByDoctorDate { get; set; }
        public Nullable<System.DateTime> WorkStationLeftByDoctorToDate { get; set; }
    }
}
